unit utransfr;

{ DO NOT EDIT THIS FILE. It was generated by the pdutil program from Parameters.tab. }

interface

uses ucollect, uparams;

const
  kGeneralLineDivisions = 1;
  kGeneralRandomSway = 2;
  kGeneralAgeAtMaturity = 4;
  kGeneralGrowthSCurve = 5;
  kGeneralAgeAtWhichFloweringStarts = 6;
  kGeneralFractionReproductiveAllocationAtMaturity = 7;
  kGeneralMaleFlowersAreSeparate = 8;
  kGeneralIsDicot = 9;
  kGeneralNumApicalInflors = 10;
  kGeneralNumAxillaryInflors = 11;
  kGeneralPhyllotacticRotationAngle = 12;
  kGeneralStartingSeedForRandomNumberGenerator = 13;
  kMeristemAndLeafArrangement = 15;
  kMeristemBranchingIndex = 16;
  kMeristemBranchingDistance = 17;
  kMeristemSecondaryBranchingIsAllowed = 18;
  kMeristemBranchingIsSympodial = 19;
  kMeristemBranchingAngle = 20;
  kMeristemDeterminateProbability = 21;
  kAxillaryBudObject3D = 23;
  kAxillaryBudScale = 24;
  kAxillaryBudObject3DXRotationBeforeDraw = 25;
  kAxillaryBudObject3DYRotationBeforeDraw = 26;
  kAxillaryBudObject3DZRotationBeforeDraw = 27;
  kAxillaryBudFaceColor = 28;
  kAxillaryBudBackfaceColor = 29;
  kInternodeFaceColor = 31;
  kInternodeFirstInternodeCurvingIndex = 32;
  kInternodeCurvingIndex = 33;
  kInternodeLengthAtOptimalFinalBiomassAndExpansion_mm = 35;
  kInternodeWidthAtOptimalFinalBiomassAndExpansion_mm = 36;
  kInternodeOptimalFinalBiomass = 38;
  kInternodeMinDaysToCreateInternode = 39;
  kInternodeMaxDaysToCreateInternodeIfOverMinFraction = 40;
  kInternodeMinFractionOfOptimalInitialBiomassToCreateInternode_frn = 41;
  kInternodeCanRecoverFromStuntingDuringCreation = 42;
  kInternodeMinDaysToAccumulateBiomass = 44;
  kInternodeMaxDaysToAccumulateBiomass = 45;
  kInternodeLengthMultiplierDueToBolting = 47;
  kInternodeBoltingMinDaysToBolt = 48;
  kLeafObject3D = 50;
  kLeafScaleAtOptimalBiomass = 51;
  kLeafObject3DXRotationBeforeDraw = 52;
  kLeafObject3DYRotationBeforeDraw = 53;
  kLeafObject3DZRotationBeforeDraw = 54;
  kLeafFaceColor = 55;
  kLeafBackfaceColor = 56;
  kLeafCompoundNumLeaflets = 58;
  kLeafCompoundPinnateOrPalmate = 59;
  kLeafCompoundPinnateArrangement = 60;
  kLeafCompoundRachisToPetioleRatio = 61;
  kLeafCompoundBendAngleAtStart = 62;
  kLeafCompoundBendAngleAtFullSize = 63;
  kLeafPetioleAngle = 65;
  kLeafPetioleColor = 66;
  kLeafPetioleLengthAtOptimalBiomass_mm = 67;
  kLeafPetioleWidthAtOptimalBiomass_mm = 68;
  kLeafPetioleTaperIndex = 69;
  kStipuleNumSections = 71;
  kStipuleObject3D = 72;
  kStipuleScaleAtOptimalLeafBiomass = 73;
  kStipuleObject3DXRotationBeforeDraw = 74;
  kStipuleObject3DYRotationBeforeDraw = 75;
  kStipuleObject3DZRotationBeforeDraw = 76;
  kStipuleFaceColor = 77;
  kStipuleBackfaceColor = 78;
  kStipuleAngleFromStem = 79;
  kLeafOptimalBiomass = 81;
  kLeafSCurve = 82;
  kLeafOptimalFractionOfOptimalBiomassAtCreation_frn = 83;
  kLeafMinDaysToGrow = 85;
  kLeafMaxDaysToGrow = 86;
  kSeedlingLeafObject3D = 88;
  kSeedlingLeafScale = 89;
  kSeedlingLeafObject3DXRotationBeforeDraw = 90;
  kSeedlingLeafObject3DYRotationBeforeDraw = 91;
  kSeedlingLeafObject3DZRotationBeforeDraw = 92;
  kSeedlingLeafFaceColor = 93;
  kSeedlingLeafBackfaceColor = 94;
  kSeedlingLeafNodesOnStemWhenFallsOff = 96;
  kFlowerNumPetalsFemale = 98;
  kFlowerFemaleObject3D = 99;
  kFlowerScaleAtFullSizeFemale = 100;
  kFlowerFemaleObject3DXRotationBeforeDraw = 101;
  kFlowerFemaleObject3DYRotationBeforeDraw = 102;
  kFlowerFemaleObject3DZRotationBeforeDraw = 103;
  kFlowerFemaleFaceColor = 104;
  kFlowerFemaleBackfaceColor = 105;
  kFlowerPetalsAreRadiallyArrangedFemale = 106;
  kFlowerFemaleObject3DPullbackAngle = 107;
  kFlowerOptimalBiomassFemale = 109;
  kFlowerMinFractOptBiomassToOpenFlowerFemale = 110;
  kFlowerMinFractionOfOptimalBiomassToCreateFruitFemale = 111;
  kFlowerMinDaysToGrowFemale = 113;
  kFlowerMaxDaysToGrowIfOverMinFractionFemale = 114;
  kFlowerMinDaysBeforeOpeningFemale = 115;
  kFlowerMinDaysBeforeSettingFruit = 116;
  kFlowerDaysBeforeDropFemale = 117;
  kInflorescenceNumFlowersOnMainBranchFemale = 119;
  kInflorescenceNumFlowersPerBranchFemale = 120;
  kInflorescenceNumBranchesFemale = 121;
  kInflorescenceFemaleStalkColor = 122;
  kInflorescenceFemalePedicelColor = 123;
  kInflorescenceBranchesAreAlternateFemale = 124;
  kInflorescenceBranchAngleFemale = 125;
  kInflorescenceInternodeAngleFemale = 126;
  kInflorescencePedicelAngleFemale = 127;
  kInflorescencePeduncleAngleFromVegetativeStemFemale = 128;
  kInflorescencePeduncleAngleFromVegetativeStemApicalFemale = 129;
  kInflorescenceFlowersSpiralOnStemFemale = 130;
  kInflorescenceIsHeadFemale = 131;
  kInflorescenceTerminalStalkLengthFemale = 133;
  kInflorescencePeduncleLengthFemale = 134;
  kInflorescenceInternodeLengthFemale = 135;
  kInflorescencePedicelLengthFemale = 136;
  kInflorescenceInternodeWidthFemale = 137;
  kInflorescencePedicelTaperIndexFemale = 138;
  kInflorescenceIsTerminalFemale = 140;
  kInflorescenceBiomassRequiredFemale = 141;
  kInflorescenceMinFractOptBiomassToCreateFemale = 142;
  kInflorescenceMinFractOptBiomassForFlowersFemale = 143;
  kInflorescenceDaysToAllFlowersShowingFemale = 145;
  kInflorescenceFlowersDrawTopToBottomFemale = 146;
  kInflorescenceMinDaysToCreateInflorescenceFemale = 147;
  kInflorescenceMaxDaysToCreateIfOverMinFractFemale = 148;
  kInflorescenceMinDaysToGrowFemale = 149;
  kInflorescenceMaxDaysToGrowFemale = 150;
  kInflorescenceFemaleBractNumBracts = 152;
  kInflorescenceFemaleBractObject3D = 153;
  kInflorescenceFemaleBractScaleAtFullSize = 154;
  kInflorescenceFemaleBractObject3DXRotationBeforeDraw = 155;
  kInflorescenceFemaleBractObject3DYRotationBeforeDraw = 156;
  kInflorescenceFemaleBractObject3DZRotationBeforeDraw = 157;
  kInflorescenceFemaleBractFaceColor = 158;
  kInflorescenceFemaleBractBackfaceColor = 159;
  kInflorescenceFemaleBractsAreRadiallyArranged = 160;
  kInflorescenceFemaleBractObject3DPullbackAngle = 161;
  kFruitNumSections = 163;
  kFruitObject3D = 164;
  kFruitScaleAtFullSize = 165;
  kFruitObject3DXRotationBeforeDraw = 166;
  kFruitObject3DYRotationBeforeDraw = 167;
  kFruitObject3DZRotationBeforeDraw = 168;
  kFruitSectionsAreRadiallyArranged = 169;
  kFruitUnripeFaceColor = 170;
  kFruitUnripeBackfaceColor = 171;
  kFruitRipeFaceColor = 172;
  kFruitRipeBackfaceColor = 173;
  kFruitOptimumMass_pctMPB = 175;
  kFruitSCurve = 176;
  kFruitMinDaysToGrow = 178;
  kFruitMaxDaysToGrow = 179;
  kFruitDaysToRipen = 180;
  kRootTopShowsAboveGround = 182;
  kRootTopObject3D = 183;
  kRootTopScaleAtFullSize = 184;
  kRootTopObject3DXRotationBeforeDraw = 185;
  kRootTopObject3DYRotationBeforeDraw = 186;
  kRootTopObject3DZRotationBeforeDraw = 187;
  kRootTopFaceColor = 188;
  kRootTopBackfaceColor = 189;
  kStateAge = 190;
  kStateBasePointX = 191;
  kStateBasePointY = 192;
  kStateDrawingScale = 193;
  kStateHidden = 194;
  kStateSelected = 195;
  kStateRotationX = 196;
  kStateRotationY = 197;
  kStateRotationZ = 198;
  kFlowerNumPetalsMale = 200;
  kFlowerMaleObject3D = 201;
  kFlowerScaleAtFullSizeMale = 202;
  kFlowerMaleObject3DXRotationBeforeDraw = 203;
  kFlowerMaleObject3DYRotationBeforeDraw = 204;
  kFlowerMaleObject3DZRotationBeforeDraw = 205;
  kFlowerMaleFaceColor = 206;
  kFlowerMaleBackfaceColor = 207;
  kFlowerPetalsAreRadiallyArrangedMale = 208;
  kFlowerMaleObject3DPullbackAngle = 209;
  kFlowerOptimalBiomassMale = 211;
  kFlowerMinFractOptBiomassToOpenFlowerMale = 212;
  kFlowerMinDaysToGrowMale = 214;
  kFlowerMaxDaysToGrowIfOverMinFractionMale = 215;
  kFlowerMinDaysBeforeOpeningMale = 216;
  kFlowerDaysBeforeDropMale = 217;
  kFlowerNumStamensMale = 219;
  kFlowerFilamentLengthMale = 220;
  kFlowerFilamentWidthMale = 221;
  kFlowerFilamentTaperIndexMale = 222;
  kFlowerFilamentColorMale = 223;
  kFlowerAntherMaleObject3DPullbackAngle = 224;
  kFlowerAntherNumSectionsMale = 225;
  kFlowerMaleAntherObject3D = 226;
  kFlowerAntherScaleAtFullSizeMale = 227;
  kFlowerMaleAntherObject3DXRotationBeforeDraw = 228;
  kFlowerMaleAntherObject3DYRotationBeforeDraw = 229;
  kFlowerMaleAntherObject3DZRotationBeforeDraw = 230;
  kFlowerAntherMaleFaceColor = 231;
  kFlowerAntherMaleBackfaceColor = 232;
  kFlowerAntherSectionsAreRadiallyArrangedMale = 233;
  kFlowerSepalNumPetalsMale = 235;
  kFlowerMaleSepalObject3D = 236;
  kFlowerSepalScaleAtFullSizeMale = 237;
  kFlowerMaleSepalObject3DXRotationBeforeDraw = 238;
  kFlowerMaleSepalObject3DYRotationBeforeDraw = 239;
  kFlowerMaleSepalObject3DZRotationBeforeDraw = 240;
  kFlowerSepalMaleFaceColor = 241;
  kFlowerSepalMaleBackfaceColor = 242;
  kFlowerSepalPetalsAreRadiallyArrangedMale = 243;
  kFlowerSepalMaleObject3DPullbackAngle = 244;
  kFlowerMaleBudOption = 246;
  kFlowerBudNumPetalsMale = 247;
  kFlowerMaleBudObject3D = 248;
  kFlowerBudScaleAtFullSizeMale = 249;
  kFlowerMaleBudObject3DXRotationBeforeDraw = 250;
  kFlowerMaleBudObject3DYRotationBeforeDraw = 251;
  kFlowerMaleBudObject3DZRotationBeforeDraw = 252;
  kFlowerBudMaleFaceColor = 253;
  kFlowerBudMaleBackfaceColor = 254;
  kFlowerBudPetalsAreRadiallyArrangedMale = 255;
  kFlowerBudMaleObject3DPullbackAngle = 256;
  kInflorescenceNumFlowersOnMainBranchMale = 258;
  kInflorescenceNumFlowersPerBranchMale = 259;
  kInflorescenceNumBranchesMale = 260;
  kInflorescenceMaleStalkColor = 261;
  kInflorescenceMalePedicelColor = 262;
  kInflorescenceBranchesAreAlternateMale = 263;
  kInflorescenceBranchAngleMale = 264;
  kInflorescenceInternodeAngleMale = 265;
  kInflorescencePedicelAngleMale = 266;
  kInflorescencePeduncleAngleFromVegetativeStemMale = 267;
  kInflorescencePeduncleAngleFromVegetativeStemApicalMale = 268;
  kInflorescenceFlowersSpiralOnStemMale = 269;
  kInflorescenceIsHeadMale = 270;
  kInflorescenceTerminalStalkLengthMale = 272;
  kInflorescencePeduncleLengthMale = 273;
  kInflorescenceInternodeLengthMale = 274;
  kInflorescencePedicelLengthMale = 275;
  kInflorescenceInternodeWidthMale = 276;
  kInflorescencePedicelTaperIndexMale = 277;
  kInflorescenceIsTerminalMale = 279;
  kInflorescenceBiomassRequiredMale = 280;
  kInflorescenceMinFractOptBiomassToCreateMale = 281;
  kInflorescenceMinFractOptBiomassForFlowersMale = 282;
  kInflorescenceDaysToAllFlowersShowingMale = 284;
  kInflorescenceFlowersDrawTopToBottomMale = 285;
  kInflorescenceMinDaysToCreateInflorescenceMale = 286;
  kInflorescenceMaxDaysToCreateIfOverMinFractMale = 287;
  kInflorescenceMinDaysToGrowMale = 288;
  kInflorescenceMaxDaysToGrowMale = 289;
  kInflorescenceMaleBractNumBracts = 291;
  kInflorescenceMaleBractObject3D = 292;
  kInflorescenceMaleBractScaleAtFullSize = 293;
  kInflorescenceMaleBractObject3DXRotationBeforeDraw = 294;
  kInflorescenceMaleBractObject3DYRotationBeforeDraw = 295;
  kInflorescenceMaleBractObject3DZRotationBeforeDraw = 296;
  kInflorescenceMaleBractFaceColor = 297;
  kInflorescenceMaleBractBackfaceColor = 298;
  kInflorescenceMaleBractsAreRadiallyArranged = 299;
  kInflorescenceMaleBractObject3DPullbackAngle = 300;
  kFlowerNumPistilsFemale = 302;
  kFlowerStyleLengthFemale = 303;
  kFlowerStyleWidthFemale = 304;
  kFlowerStyleTaperIndexFemale = 305;
  kFlowerStigmaFemaleObject3DPullbackAngle = 306;
  kFlowerStyleColorFemale = 307;
  kFlowerStigmaNumSectionsFemale = 308;
  kFlowerFemaleStigmaObject3D = 309;
  kFlowerStigmaScaleAtFullSizeFemale = 310;
  kFlowerFemaleStigmaObject3DXRotationBeforeDraw = 311;
  kFlowerFemaleStigmaObject3DYRotationBeforeDraw = 312;
  kFlowerFemaleStigmaObject3DZRotationBeforeDraw = 313;
  kFlowerStigmaFemaleFaceColor = 314;
  kFlowerStigmaFemaleBackfaceColor = 315;
  kFlowerStigmaSectionsAreRadiallyArrangedFemale = 316;
  kFlowerNumStamensFemale = 318;
  kFlowerFilamentLengthFemale = 319;
  kFlowerFilamentWidthFemale = 320;
  kFlowerFilamentTaperIndexFemale = 321;
  kFlowerFilamentColorFemale = 322;
  kFlowerAntherFemaleObject3DPullbackAngle = 323;
  kFlowerAntherNumSectionsFemale = 324;
  kFlowerFemaleAntherObject3D = 325;
  kFlowerAntherScaleAtFullSizeFemale = 326;
  kFlowerFemaleAntherObject3DXRotationBeforeDraw = 327;
  kFlowerFemaleAntherObject3DYRotationBeforeDraw = 328;
  kFlowerFemaleAntherObject3DZRotationBeforeDraw = 329;
  kFlowerAntherFemaleFaceColor = 330;
  kFlowerAntherFemaleBackfaceColor = 331;
  kFlowerAntherSectionsAreRadiallyArrangedFemale = 332;
  kFlowerPetal2NumPetalsFemale = 334;
  kFlowerFemalePetal2Object3D = 335;
  kFlowerPetal2ScaleAtFullSizeFemale = 336;
  kFlowerFemalePetal2Object3DXRotationBeforeDraw = 337;
  kFlowerFemalePetal2Object3DYRotationBeforeDraw = 338;
  kFlowerFemalePetal2Object3DZRotationBeforeDraw = 339;
  kFlowerPetal2FemaleFaceColor = 340;
  kFlowerPetal2FemaleBackfaceColor = 341;
  kFlowerPetal2PetalsAreRadiallyArrangedFemale = 342;
  kFlowerPetal2FemaleObject3DPullbackAngle = 343;
  kFlowerPetal3NumPetalsFemale = 345;
  kFlowerFemalePetal3Object3D = 346;
  kFlowerPetal3ScaleAtFullSizeFemale = 347;
  kFlowerFemalePetal3Object3DXRotationBeforeDraw = 348;
  kFlowerFemalePetal3Object3DYRotationBeforeDraw = 349;
  kFlowerFemalePetal3Object3DZRotationBeforeDraw = 350;
  kFlowerPetal3FemaleFaceColor = 351;
  kFlowerPetal3FemaleBackfaceColor = 352;
  kFlowerPetal3PetalsAreRadiallyArrangedFemale = 353;
  kFlowerPetal3FemaleObject3DPullbackAngle = 354;
  kFlowerPetal4NumPetalsFemale = 356;
  kFlowerFemalePetal4Object3D = 357;
  kFlowerPetal4ScaleAtFullSizeFemale = 358;
  kFlowerFemalePetal4Object3DXRotationBeforeDraw = 359;
  kFlowerFemalePetal4Object3DYRotationBeforeDraw = 360;
  kFlowerFemalePetal4Object3DZRotationBeforeDraw = 361;
  kFlowerPetal4FemaleFaceColor = 362;
  kFlowerPetal4FemaleBackfaceColor = 363;
  kFlowerPetal4PetalsAreRadiallyArrangedFemale = 364;
  kFlowerPetal4FemaleObject3DPullbackAngle = 365;
  kFlowerPetal5NumPetalsFemale = 367;
  kFlowerFemalePetal5Object3D = 368;
  kFlowerPetal5ScaleAtFullSizeFemale = 369;
  kFlowerFemalePetal5Object3DXRotationBeforeDraw = 370;
  kFlowerFemalePetal5Object3DYRotationBeforeDraw = 371;
  kFlowerFemalePetal5Object3DZRotationBeforeDraw = 372;
  kFlowerPetal5FemaleFaceColor = 373;
  kFlowerPetal5FemaleBackfaceColor = 374;
  kFlowerPetal5PetalsAreRadiallyArrangedFemale = 375;
  kFlowerPetal5FemaleObject3DPullbackAngle = 376;
  kFlowerSepalNumPetalsFemale = 378;
  kFlowerFemaleSepalObject3D = 379;
  kFlowerSepalScaleAtFullSizeFemale = 380;
  kFlowerFemaleSepalObject3DXRotationBeforeDraw = 381;
  kFlowerFemaleSepalObject3DYRotationBeforeDraw = 382;
  kFlowerFemaleSepalObject3DZRotationBeforeDraw = 383;
  kFlowerSepalFemaleFaceColor = 384;
  kFlowerSepalFemaleBackfaceColor = 385;
  kFlowerSepalPetalsAreRadiallyArrangedFemale = 386;
  kFlowerSepalFemaleObject3DPullbackAngle = 387;
  kFlowerFemaleBudOption = 389;
  kFlowerBudNumPetalsFemale = 390;
  kFlowerFemaleBudObject3D = 391;
  kFlowerBudScaleAtFullSizeFemale = 392;
  kFlowerFemaleBudObject3DXRotationBeforeDraw = 393;
  kFlowerFemaleBudObject3DYRotationBeforeDraw = 394;
  kFlowerFemaleBudObject3DZRotationBeforeDraw = 395;
  kFlowerBudFemaleFaceColor = 396;
  kFlowerBudFemaleBackfaceColor = 397;
  kFlowerBudPetalsAreRadiallyArrangedFemale = 398;
  kFlowerBudFemaleObject3DPullbackAngle = 399;

procedure Plant_directTransferField(plantProxy: TObject; var v;
  d, fieldID, ft, index: smallint; updateList: TListCollection);
procedure Plant_directTransferField_SecondPart(plantProxy: TObject; var v;
  d, fieldID, ft, index: smallint; updateList: TListCollection);

implementation

uses SysUtils, uplant, utdo, umath;

procedure Plant_directTransferField(plantProxy: TObject; var v; d, fieldID, ft, index: smallint; updateList: TListCollection);
  var plant: PdPlant;
  begin
  if plantProxy = nil then
    raise Exception.create('Plant_directTransferField: nil plant');
  plant := plantProxy as PdPlant;
  with plant do case fieldID of
    kGeneralLineDivisions: 
      MFD(pGeneral.LineDivisions, v, ft, d);
    kGeneralRandomSway: 
      MFD(pGeneral.randomSway, v, ft, d);
    kGeneralAgeAtMaturity: 
      MFD(pGeneral.ageAtMaturity, v, ft, d);
    kGeneralGrowthSCurve: 
      transferSCurveValue(d, pGeneral.growthSCurve, index, v);
    kGeneralAgeAtWhichFloweringStarts: 
      MFD(pGeneral.ageAtWhichFloweringStarts, v, ft, d);
    kGeneralFractionReproductiveAllocationAtMaturity: 
      MFD(pGeneral.fractionReproductiveAllocationAtMaturity_frn, v, ft, d);
    kGeneralMaleFlowersAreSeparate: 
      MFD(pGeneral.MaleFlowersAreSeparate, v, ft, d);
    kGeneralIsDicot: 
      MFD(pGeneral.IsDicot, v, ft, d);
    kGeneralNumApicalInflors: 
      MFD(pGeneral.NumApicalInflors, v, ft, d);
    kGeneralNumAxillaryInflors: 
      MFD(pGeneral.NumAxillaryInflors, v, ft, d);
    kGeneralPhyllotacticRotationAngle: 
      MFD(pGeneral.phyllotacticRotationAngle, v, ft, d);
    kGeneralStartingSeedForRandomNumberGenerator: 
      MFD(pGeneral.startingSeedForRandomNumberGenerator, v, ft, d);
    kMeristemAndLeafArrangement: 
      MFD(pMeristem.branchingAndLeafArrangement, v, ft, d);
    kMeristemBranchingIndex: 
      MFD(pMeristem.BranchingIndex, v, ft, d);
    kMeristemBranchingDistance: 
      MFD(pMeristem.BranchingDistance, v, ft, d);
    kMeristemSecondaryBranchingIsAllowed: 
      MFD(pMeristem.secondaryBranchingIsAllowed, v, ft, d);
    kMeristemBranchingIsSympodial: 
      MFD(pMeristem.BranchingIsSympodial, v, ft, d);
    kMeristemBranchingAngle: 
      MFD(pMeristem.branchingAngle, v, ft, d);
    kMeristemDeterminateProbability: 
      MFD(pMeristem.DeterminateProbability, v, ft, d);
    kAxillaryBudObject3D: 
      transferObject3D(d, pAxillaryBud.tdoParams.object3D, KfObject3D(v));
    kAxillaryBudScale: 
      MFD(pAxillaryBud.tdoParams.scaleAtFullSize, v, ft, d);
    kAxillaryBudObject3DXRotationBeforeDraw: 
      MFD(pAxillaryBud.tdoParams.xRotationBeforeDraw, v, ft, d);
    kAxillaryBudObject3DYRotationBeforeDraw: 
      MFD(pAxillaryBud.tdoParams.yRotationBeforeDraw, v, ft, d);
    kAxillaryBudObject3DZRotationBeforeDraw: 
      MFD(pAxillaryBud.tdoParams.zRotationBeforeDraw, v, ft, d);
    kAxillaryBudFaceColor: 
      MFD(pAxillaryBud.tdoParams.faceColor, v, ft, d);
    kAxillaryBudBackfaceColor: 
      MFD(pAxillaryBud.tdoParams.backfaceColor, v, ft, d);
    kInternodeFaceColor: 
      MFD(pInternode.FaceColor, v, ft, d);
    kInternodeFirstInternodeCurvingIndex: 
      MFD(pInternode.firstInternodeCurvingIndex, v, ft, d);
    kInternodeCurvingIndex: 
      MFD(pInternode.curvingIndex, v, ft, d);
    kInternodeLengthAtOptimalFinalBiomassAndExpansion_mm: 
      MFD(pInternode.LengthAtOptimalFinalBiomassAndExpansion_mm, v, ft, d);
    kInternodeWidthAtOptimalFinalBiomassAndExpansion_mm: 
      MFD(pInternode.WidthAtOptimalFinalBiomassAndExpansion_mm, v, ft, d);
    kInternodeOptimalFinalBiomass: 
      MFD(pInternode.OptimalFinalBiomass_pctMPB, v, ft, d);
    kInternodeMinDaysToCreateInternode: 
      MFD(pInternode.MinDaysToCreateInternode, v, ft, d);
    kInternodeMaxDaysToCreateInternodeIfOverMinFraction: 
      MFD(pInternode.MaxDaysToCreateInternodeIfOverMinFraction, v, ft, d);
    kInternodeMinFractionOfOptimalInitialBiomassToCreateInternode_frn: 
      MFD(pInternode.MinFractionOfOptimalInitialBiomassToCreateInternode_frn, v, ft, d);
    kInternodeCanRecoverFromStuntingDuringCreation: 
      MFD(pInternode.CanRecoverFromStuntingDuringCreation, v, ft, d);
    kInternodeMinDaysToAccumulateBiomass: 
      MFD(pInternode.MinDaysToAccumulateBiomass, v, ft, d);
    kInternodeMaxDaysToAccumulateBiomass: 
      MFD(pInternode.MaxDaysToAccumulateBiomass, v, ft, d);
    kInternodeLengthMultiplierDueToBolting: 
      MFD(pInternode.LengthMultiplierDueToBolting, v, ft, d);
    kInternodeBoltingMinDaysToBolt: 
      MFD(pInternode.MinDaysToBolt, v, ft, d);
    kLeafObject3D: 
      transferObject3D(d, pLeaf.leafTdoParams.object3D, KfObject3D(v));
    kLeafScaleAtOptimalBiomass: 
      MFD(pLeaf.leafTdoParams.scaleAtFullSize, v, ft, d);
    kLeafObject3DXRotationBeforeDraw: 
      MFD(pLeaf.leafTdoParams.xRotationBeforeDraw, v, ft, d);
    kLeafObject3DYRotationBeforeDraw: 
      MFD(pLeaf.leafTdoParams.yRotationBeforeDraw, v, ft, d);
    kLeafObject3DZRotationBeforeDraw: 
      MFD(pLeaf.leafTdoParams.zRotationBeforeDraw, v, ft, d);
    kLeafFaceColor: 
      MFD(pLeaf.leafTdoParams.FaceColor, v, ft, d);
    kLeafBackfaceColor: 
      MFD(pLeaf.leafTdoParams.BackfaceColor, v, ft, d);
    kLeafCompoundNumLeaflets: 
      MFD(pLeaf.CompoundNumLeaflets, v, ft, d);
    kLeafCompoundPinnateOrPalmate: 
      MFD(pLeaf.CompoundPinnateOrPalmate, v, ft, d);
    kLeafCompoundPinnateArrangement: 
      MFD(pLeaf.compoundPinnateLeafletArrangement, v, ft, d);
    kLeafCompoundRachisToPetioleRatio: 
      MFD(pLeaf.CompoundRachisToPetioleRatio, v, ft, d);
    kLeafCompoundBendAngleAtStart: 
      MFD(pLeaf.compoundCurveAngleAtStart, v, ft, d);
    kLeafCompoundBendAngleAtFullSize: 
      MFD(pLeaf.compoundCurveAngleAtFullSize, v, ft, d);
    kLeafPetioleAngle: 
      MFD(pLeaf.PetioleAngle, v, ft, d);
    kLeafPetioleColor: 
      MFD(pLeaf.PetioleColor, v, ft, d);
    kLeafPetioleLengthAtOptimalBiomass_mm: 
      MFD(pLeaf.PetioleLengthAtOptimalBiomass_mm, v, ft, d);
    kLeafPetioleWidthAtOptimalBiomass_mm: 
      MFD(pLeaf.PetioleWidthAtOptimalBiomass_mm, v, ft, d);
    kLeafPetioleTaperIndex: 
      MFD(pLeaf.petioleTaperIndex, v, ft, d);
    kStipuleNumSections: 
      MFD(pLeaf.stipuleTdoParams.repetitions, v, ft, d);
    kStipuleObject3D: 
      transferObject3D(d, pLeaf.stipuleTdoParams.object3D, KfObject3D(v));
    kStipuleScaleAtOptimalLeafBiomass: 
      MFD(pLeaf.stipuleTdoParams.scaleAtFullSize, v, ft, d);
    kStipuleObject3DXRotationBeforeDraw: 
      MFD(pLeaf.stipuleTdoParams.xRotationBeforeDraw, v, ft, d);
    kStipuleObject3DYRotationBeforeDraw: 
      MFD(pLeaf.stipuleTdoParams.yRotationBeforeDraw, v, ft, d);
    kStipuleObject3DZRotationBeforeDraw: 
      MFD(pLeaf.stipuleTdoParams.zRotationBeforeDraw, v, ft, d);
    kStipuleFaceColor: 
      MFD(pLeaf.stipuleTdoParams.FaceColor, v, ft, d);
    kStipuleBackfaceColor: 
      MFD(pLeaf.stipuleTdoParams.BackfaceColor, v, ft, d);
    kStipuleAngleFromStem: 
      MFD(pLeaf.stipuleTdoParams.pullBackAngle, v, ft, d);
    kLeafOptimalBiomass: 
      MFD(pLeaf.optimalBiomass_pctMPB, v, ft, d);
    kLeafSCurve: 
      transferSCurveValue(d, pLeaf.sCurveParams, index, v);
    kLeafOptimalFractionOfOptimalBiomassAtCreation_frn: 
      MFD(pLeaf.optimalFractionOfOptimalBiomassAtCreation_frn, v, ft, d);
    kLeafMinDaysToGrow: 
      MFD(pLeaf.minDaysToGrow, v, ft, d);
    kLeafMaxDaysToGrow: 
      MFD(pLeaf.MaxDaysToGrow, v, ft, d);
    kSeedlingLeafObject3D: 
      transferObject3D(d, pSeedlingLeaf.leafTdoParams.object3D, KfObject3D(v));
    kSeedlingLeafScale: 
      MFD(pSeedlingLeaf.leafTdoParams.scaleAtFullSize, v, ft, d);
    kSeedlingLeafObject3DXRotationBeforeDraw: 
      MFD(pSeedlingLeaf.leafTdoParams.xRotationBeforeDraw, v, ft, d);
    kSeedlingLeafObject3DYRotationBeforeDraw: 
      MFD(pSeedlingLeaf.leafTdoParams.yRotationBeforeDraw, v, ft, d);
    kSeedlingLeafObject3DZRotationBeforeDraw: 
      MFD(pSeedlingLeaf.leafTdoParams.zRotationBeforeDraw, v, ft, d);
    kSeedlingLeafFaceColor: 
      MFD(pSeedlingLeaf.leafTdoParams.FaceColor, v, ft, d);
    kSeedlingLeafBackfaceColor: 
      MFD(pSeedlingLeaf.leafTdoParams.BackfaceColor, v, ft, d);
    kSeedlingLeafNodesOnStemWhenFallsOff: 
      MFD(pSeedlingLeaf.NodesOnStemWhenFallsOff, v, ft, d);
    kFlowerNumPetalsFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kFirstPetals].repetitions, v, ft, d);
    kFlowerFemaleObject3D: 
      transferObject3D(d, pFlower[kGenderFemale].tdoParams[kFirstPetals].object3D, KfObject3D(v));
    kFlowerScaleAtFullSizeFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kFirstPetals].ScaleAtFullSize, v, ft, d);
    kFlowerFemaleObject3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kFirstPetals].xRotationBeforeDraw, v, ft, d);
    kFlowerFemaleObject3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kFirstPetals].yRotationBeforeDraw, v, ft, d);
    kFlowerFemaleObject3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kFirstPetals].zRotationBeforeDraw, v, ft, d);
    kFlowerFemaleFaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kFirstPetals].FaceColor, v, ft, d);
    kFlowerFemaleBackfaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kFirstPetals].BackfaceColor, v, ft, d);
    kFlowerPetalsAreRadiallyArrangedFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kFirstPetals].radiallyArranged, v, ft, d);
    kFlowerFemaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderFemale].tdoParams[kFirstPetals].pullBackAngle, v, ft, d);
    kFlowerOptimalBiomassFemale: 
      MFD(pFlower[kGenderFemale].OptimalBiomass_pctMPB, v, ft, d);
    kFlowerMinFractOptBiomassToOpenFlowerFemale: 
      MFD(pFlower[kGenderFemale].MinFractionOfOptimalBiomassToOpenFlower_frn, v, ft, d);
    kFlowerMinFractionOfOptimalBiomassToCreateFruitFemale: 
      MFD(pFlower[kGenderFemale].minFractionOfOptimalBiomassToCreateFruit_frn, v, ft, d);
    kFlowerMinDaysToGrowFemale: 
      MFD(pFlower[kGenderFemale].MinDaysToGrow, v, ft, d);
    kFlowerMaxDaysToGrowIfOverMinFractionFemale: 
      MFD(pFlower[kGenderFemale].MaxDaysToGrowIfOverMinFraction, v, ft, d);
    kFlowerMinDaysBeforeOpeningFemale: 
      MFD(pFlower[kGenderFemale].minDaysToOpenFlower, v, ft, d);
    kFlowerMinDaysBeforeSettingFruit: 
      MFD(pFlower[kGenderFemale].minDaysBeforeSettingFruit, v, ft, d);
    kFlowerDaysBeforeDropFemale: 
      MFD(pFlower[kGenderFemale].DaysBeforeDrop, v, ft, d);
    kInflorescenceNumFlowersOnMainBranchFemale: 
      MFD(pInflor[kGenderFemale].numFlowersOnMainBranch, v, ft, d);
    kInflorescenceNumFlowersPerBranchFemale: 
      MFD(pInflor[kGenderFemale].numFlowersPerBranch, v, ft, d);
    kInflorescenceNumBranchesFemale: 
      MFD(pInflor[kGenderFemale].NumBranches, v, ft, d);
    kInflorescenceFemaleStalkColor: 
      MFD(pInflor[kGenderFemale].StalkColor, v, ft, d);
    kInflorescenceFemalePedicelColor: 
      MFD(pInflor[kGenderFemale].pedicelColor, v, ft, d);
    kInflorescenceBranchesAreAlternateFemale: 
      MFD(pInflor[kGenderFemale].BranchesAreAlternate, v, ft, d);
    kInflorescenceBranchAngleFemale: 
      MFD(pInflor[kGenderFemale].BranchAngle, v, ft, d);
    kInflorescenceInternodeAngleFemale: 
      MFD(pInflor[kGenderFemale].angleBetweenInternodes, v, ft, d);
    kInflorescencePedicelAngleFemale: 
      MFD(pInflor[kGenderFemale].PedicelAngle, v, ft, d);
    kInflorescencePeduncleAngleFromVegetativeStemFemale: 
      MFD(pInflor[kGenderFemale].peduncleAngleFromVegetativeStem, v, ft, d);
    kInflorescencePeduncleAngleFromVegetativeStemApicalFemale: 
      MFD(pInflor[kGenderFemale].apicalStalkAngleFromVegetativeStem, v, ft, d);
    kInflorescenceFlowersSpiralOnStemFemale: 
      MFD(pInflor[kGenderFemale].FlowersSpiralOnStem, v, ft, d);
    kInflorescenceIsHeadFemale: 
      MFD(pInflor[kGenderFemale].IsHead, v, ft, d);
    kInflorescenceTerminalStalkLengthFemale: 
      MFD(pInflor[kGenderFemale].TerminalStalkLength_mm, v, ft, d);
    kInflorescencePeduncleLengthFemale: 
      MFD(pInflor[kGenderFemale].PeduncleLength_mm, v, ft, d);
    kInflorescenceInternodeLengthFemale: 
      MFD(pInflor[kGenderFemale].InternodeLength_mm, v, ft, d);
    kInflorescencePedicelLengthFemale: 
      MFD(pInflor[kGenderFemale].PedicelLength_mm, v, ft, d);
    kInflorescenceInternodeWidthFemale: 
      MFD(pInflor[kGenderFemale].InternodeWidth_mm, v, ft, d);
    kInflorescencePedicelTaperIndexFemale: 
      MFD(pInflor[kGenderFemale].pedicelTaperIndex, v, ft, d);
    kInflorescenceIsTerminalFemale: 
      MFD(pInflor[kGenderFemale].IsTerminal, v, ft, d);
    kInflorescenceBiomassRequiredFemale: 
      MFD(pInflor[kGenderFemale].optimalBiomass_pctMPB, v, ft, d);
    kInflorescenceMinFractOptBiomassToCreateFemale: 
      MFD(pInflor[kGenderFemale].MinFractionOfOptimalBiomassToCreateInflorescence_frn, v, ft, d);
    kInflorescenceMinFractOptBiomassForFlowersFemale: 
      MFD(pInflor[kGenderFemale].MinFractionOfOptimalBiomassToMakeFlowers_frn, v, ft, d);
    kInflorescenceDaysToAllFlowersShowingFemale: 
      MFD(pInflor[kGenderFemale].daysToAllFlowersCreated, v, ft, d);
    kInflorescenceFlowersDrawTopToBottomFemale: 
      MFD(pInflor[kGenderFemale].FlowersDrawTopToBottom, v, ft, d);
    kInflorescenceMinDaysToCreateInflorescenceFemale: 
      MFD(pInflor[kGenderFemale].MinDaysToCreateInflorescence, v, ft, d);
    kInflorescenceMaxDaysToCreateIfOverMinFractFemale: 
      MFD(pInflor[kGenderFemale].MaxDaysToCreateInflorescenceIfOverMinFraction, v, ft, d);
    kInflorescenceMinDaysToGrowFemale: 
      MFD(pInflor[kGenderFemale].MinDaysToGrow, v, ft, d);
    kInflorescenceMaxDaysToGrowFemale: 
      MFD(pInflor[kGenderFemale].MaxDaysToGrow, v, ft, d);
    kInflorescenceFemaleBractNumBracts: 
      MFD(pInflor[kGenderFemale].bractTdoParams.repetitions, v, ft, d);
    kInflorescenceFemaleBractObject3D: 
      transferObject3D(d, pInflor[kGenderFemale].bractTdoParams.object3D, KfObject3D(v));
    kInflorescenceFemaleBractScaleAtFullSize: 
      MFD(pInflor[kGenderFemale].bractTdoParams.scaleAtFullSize, v, ft, d);
    kInflorescenceFemaleBractObject3DXRotationBeforeDraw: 
      MFD(pInflor[kGenderFemale].bractTdoParams.xRotationBeforeDraw, v, ft, d);
    kInflorescenceFemaleBractObject3DYRotationBeforeDraw: 
      MFD(pInflor[kGenderFemale].bractTdoParams.yRotationBeforeDraw, v, ft, d);
    kInflorescenceFemaleBractObject3DZRotationBeforeDraw: 
      MFD(pInflor[kGenderFemale].bractTdoParams.zRotationBeforeDraw, v, ft, d);
    kInflorescenceFemaleBractFaceColor: 
      MFD(pInflor[kGenderFemale].bractTdoParams.faceColor, v, ft, d);
    kInflorescenceFemaleBractBackfaceColor: 
      MFD(pInflor[kGenderFemale].bractTdoParams.backfaceColor, v, ft, d);
    kInflorescenceFemaleBractsAreRadiallyArranged: 
      MFD(pInflor[kGenderFemale].bractTdoParams.radiallyArranged, v, ft, d);
    kInflorescenceFemaleBractObject3DPullbackAngle: 
      MFD(pInflor[kGenderFemale].bractTdoParams.pullBackAngle, v, ft, d);
    kFruitNumSections: 
      MFD(pFruit.tdoParams.repetitions, v, ft, d);
    kFruitObject3D: 
      transferObject3D(d, pFruit.tdoParams.object3D, KfObject3D(v));
    kFruitScaleAtFullSize: 
      MFD(pFruit.tdoParams.scaleAtFullSize, v, ft, d);
    kFruitObject3DXRotationBeforeDraw: 
      MFD(pFruit.tdoParams.xRotationBeforeDraw, v, ft, d);
    kFruitObject3DYRotationBeforeDraw: 
      MFD(pFruit.tdoParams.yRotationBeforeDraw, v, ft, d);
    kFruitObject3DZRotationBeforeDraw: 
      MFD(pFruit.tdoParams.zRotationBeforeDraw, v, ft, d);
    kFruitSectionsAreRadiallyArranged: 
      MFD(pFruit.tdoParams.radiallyArranged, v, ft, d);
    kFruitUnripeFaceColor: 
      MFD(pFruit.tdoParams.alternateFaceColor, v, ft, d);
    kFruitUnripeBackfaceColor: 
      MFD(pFruit.tdoParams.alternateBackfaceColor, v, ft, d);
    kFruitRipeFaceColor: 
      MFD(pFruit.tdoParams.faceColor, v, ft, d);
    kFruitRipeBackfaceColor: 
      MFD(pFruit.tdoParams.backfaceColor, v, ft, d);
    kFruitOptimumMass_pctMPB: 
      MFD(pFruit.optimalBiomass_pctMPB, v, ft, d);
    kFruitSCurve: 
      transferSCurveValue(d, pFruit.sCurveParams, index, v);
    kFruitMinDaysToGrow: 
      MFD(pFruit.MinDaysToGrow, v, ft, d);
    kFruitMaxDaysToGrow: 
      MFD(pFruit.MaxDaysToGrow, v, ft, d);
    kFruitDaysToRipen: 
      MFD(pFruit.DaysToRipen, v, ft, d);
    kRootTopShowsAboveGround: 
      MFD(pRoot.ShowsAboveGround, v, ft, d);
    kRootTopObject3D: 
      transferObject3D(d, pRoot.tdoParams.object3D, KfObject3D(v));
    kRootTopScaleAtFullSize: 
      MFD(pRoot.tdoParams.scaleAtFullSize, v, ft, d);
    kRootTopObject3DXRotationBeforeDraw: 
      MFD(pRoot.tdoParams.xRotationBeforeDraw, v, ft, d);
    kRootTopObject3DYRotationBeforeDraw: 
      MFD(pRoot.tdoParams.yRotationBeforeDraw, v, ft, d);
    kRootTopObject3DZRotationBeforeDraw: 
      MFD(pRoot.tdoParams.zRotationBeforeDraw, v, ft, d);
    kRootTopFaceColor: 
      MFD(pRoot.tdoParams.faceColor, v, ft, d);
    kRootTopBackfaceColor: 
      MFD(pRoot.tdoParams.backfaceColor, v, ft, d);
    kStateAge: 
      MFD(age, v, ft, d);
    kStateBasePointX: 
      MFD(basePoint_mm.x, v, ft, d);
    kStateBasePointY: 
      MFD(basePoint_mm.y, v, ft, d);
    kStateDrawingScale: 
      MFD(drawingScale_PixelsPerMm, v, ft, d);
    kStateHidden: 
      MFD(hidden, v, ft, d);
    kStateSelected: 
      MFD(selectedWhenLastSaved, v, ft, d);
    kStateRotationX: 
      MFD(xRotation, v, ft, d);
    kStateRotationY: 
      MFD(yRotation, v, ft, d);
    kStateRotationZ: 
      MFD(zRotation, v, ft, d);
    kFlowerNumPetalsMale: 
      MFD(pFlower[kGenderMale].tdoParams[kFirstPetals].repetitions, v, ft, d);
    end;
  end;

procedure Plant_directTransferField_SecondPart(plantProxy: TObject; var v; d, fieldID, ft, index: smallint; updateList: TListCollection);
  var plant: PdPlant;
  begin
  if plantProxy = nil then
    raise Exception.create('Plant_directTransferField_SecondPart: nil plant');
  plant := plantProxy as PdPlant;
  with plant do case fieldID of
    kFlowerMaleObject3D: 
      transferObject3D(d, pFlower[kGenderMale].tdoParams[kFirstPetals].object3D, KfObject3D(v));
    kFlowerScaleAtFullSizeMale: 
      MFD(pFlower[kGenderMale].tdoParams[kFirstPetals].ScaleAtFullSize, v, ft, d);
    kFlowerMaleObject3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kFirstPetals].xRotationBeforeDraw, v, ft, d);
    kFlowerMaleObject3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kFirstPetals].yRotationBeforeDraw, v, ft, d);
    kFlowerMaleObject3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kFirstPetals].zRotationBeforeDraw, v, ft, d);
    kFlowerMaleFaceColor: 
      MFD(pFlower[kGenderMale].tdoParams[kFirstPetals].FaceColor, v, ft, d);
    kFlowerMaleBackfaceColor: 
      MFD(pFlower[kGenderMale].tdoParams[kFirstPetals].BackfaceColor, v, ft, d);
    kFlowerPetalsAreRadiallyArrangedMale: 
      MFD(pFlower[kGenderMale].tdoParams[kFirstPetals].radiallyArranged, v, ft, d);
    kFlowerMaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderMale].tdoParams[kFirstPetals].pullBackAngle, v, ft, d);
    kFlowerOptimalBiomassMale: 
      MFD(pFlower[kGenderMale].OptimalBiomass_pctMPB, v, ft, d);
    kFlowerMinFractOptBiomassToOpenFlowerMale: 
      MFD(pFlower[kGenderMale].MinFractionOfOptimalBiomassToOpenFlower_frn, v, ft, d);
    kFlowerMinDaysToGrowMale: 
      MFD(pFlower[kGenderMale].MinDaysToGrow, v, ft, d);
    kFlowerMaxDaysToGrowIfOverMinFractionMale: 
      MFD(pFlower[kGenderMale].MaxDaysToGrowIfOverMinFraction, v, ft, d);
    kFlowerMinDaysBeforeOpeningMale: 
      MFD(pFlower[kGenderMale].minDaysToOpenFlower, v, ft, d);
    kFlowerDaysBeforeDropMale: 
      MFD(pFlower[kGenderMale].DaysBeforeDrop, v, ft, d);
    kFlowerNumStamensMale: 
      MFD(pFlower[kGenderMale].numStamens, v, ft, d);
    kFlowerFilamentLengthMale: 
      MFD(pFlower[kGenderMale].filamentLength_mm, v, ft, d);
    kFlowerFilamentWidthMale: 
      MFD(pFlower[kGenderMale].filamentWidth_mm, v, ft, d);
    kFlowerFilamentTaperIndexMale: 
      MFD(pFlower[kGenderMale].filamentTaperIndex, v, ft, d);
    kFlowerFilamentColorMale: 
      MFD(pFlower[kGenderMale].filamentColor, v, ft, d);
    kFlowerAntherMaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderMale].tdoParams[kStamens].pullBackAngle, v, ft, d);
    kFlowerAntherNumSectionsMale: 
      MFD(pFlower[kGenderMale].tdoParams[kStamens].repetitions, v, ft, d);
    kFlowerMaleAntherObject3D: 
      transferObject3D(d, pFlower[kGenderMale].tdoParams[kStamens].object3D, KfObject3D(v));
    kFlowerAntherScaleAtFullSizeMale: 
      MFD(pFlower[kGenderMale].tdoParams[kStamens].scaleAtFullSize, v, ft, d);
    kFlowerMaleAntherObject3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kStamens].xRotationBeforeDraw, v, ft, d);
    kFlowerMaleAntherObject3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kStamens].yRotationBeforeDraw, v, ft, d);
    kFlowerMaleAntherObject3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kStamens].zRotationBeforeDraw, v, ft, d);
    kFlowerAntherMaleFaceColor: 
      MFD(pFlower[kGenderMale].tdoParams[kStamens].faceColor, v, ft, d);
    kFlowerAntherMaleBackfaceColor: 
      MFD(pFlower[kGenderMale].tdoParams[kStamens].backfaceColor, v, ft, d);
    kFlowerAntherSectionsAreRadiallyArrangedMale: 
      MFD(pFlower[kGenderMale].tdoParams[kStamens].radiallyArranged, v, ft, d);
    kFlowerSepalNumPetalsMale: 
      MFD(pFlower[kGenderMale].tdoParams[kSepals].repetitions, v, ft, d);
    kFlowerMaleSepalObject3D: 
      transferObject3D(d, pFlower[kGenderMale].tdoParams[kSepals].object3D, KfObject3D(v));
    kFlowerSepalScaleAtFullSizeMale: 
      MFD(pFlower[kGenderMale].tdoParams[kSepals].scaleAtFullSize, v, ft, d);
    kFlowerMaleSepalObject3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kSepals].xRotationBeforeDraw, v, ft, d);
    kFlowerMaleSepalObject3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kSepals].yRotationBeforeDraw, v, ft, d);
    kFlowerMaleSepalObject3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kSepals].zRotationBeforeDraw, v, ft, d);
    kFlowerSepalMaleFaceColor: 
      MFD(pFlower[kGenderMale].tdoParams[kSepals].faceColor, v, ft, d);
    kFlowerSepalMaleBackfaceColor: 
      MFD(pFlower[kGenderMale].tdoParams[kSepals].backfaceColor, v, ft, d);
    kFlowerSepalPetalsAreRadiallyArrangedMale: 
      MFD(pFlower[kGenderMale].tdoParams[kSepals].radiallyArranged, v, ft, d);
    kFlowerSepalMaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderMale].tdoParams[kSepals].pullBackAngle, v, ft, d);
    kFlowerMaleBudOption: 
      MFD(pFlower[kGenderMale].budDrawingOption, v, ft, d);
    kFlowerBudNumPetalsMale: 
      MFD(pFlower[kGenderMale].tdoParams[kBud].repetitions, v, ft, d);
    kFlowerMaleBudObject3D: 
      transferObject3D(d, pFlower[kGenderMale].tdoParams[kBud].object3D, KfObject3D(v));
    kFlowerBudScaleAtFullSizeMale: 
      MFD(pFlower[kGenderMale].tdoParams[kBud].scaleAtFullSize, v, ft, d);
    kFlowerMaleBudObject3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kBud].xRotationBeforeDraw, v, ft, d);
    kFlowerMaleBudObject3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kBud].yRotationBeforeDraw, v, ft, d);
    kFlowerMaleBudObject3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderMale].tdoParams[kBud].zRotationBeforeDraw, v, ft, d);
    kFlowerBudMaleFaceColor: 
      MFD(pFlower[kGenderMale].tdoParams[kBud].faceColor, v, ft, d);
    kFlowerBudMaleBackfaceColor: 
      MFD(pFlower[kGenderMale].tdoParams[kBud].backfaceColor, v, ft, d);
    kFlowerBudPetalsAreRadiallyArrangedMale: 
      MFD(pFlower[kGenderMale].tdoParams[kBud].radiallyArranged, v, ft, d);
    kFlowerBudMaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderMale].tdoParams[kBud].pullBackAngle, v, ft, d);
    kInflorescenceNumFlowersOnMainBranchMale: 
      MFD(pInflor[kGenderMale].numFlowersOnMainBranch, v, ft, d);
    kInflorescenceNumFlowersPerBranchMale: 
      MFD(pInflor[kGenderMale].numFlowersPerBranch, v, ft, d);
    kInflorescenceNumBranchesMale: 
      MFD(pInflor[kGenderMale].NumBranches, v, ft, d);
    kInflorescenceMaleStalkColor: 
      MFD(pInflor[kGenderMale].StalkColor, v, ft, d);
    kInflorescenceMalePedicelColor: 
      MFD(pInflor[kGenderMale].pedicelColor, v, ft, d);
    kInflorescenceBranchesAreAlternateMale: 
      MFD(pInflor[kGenderMale].BranchesAreAlternate, v, ft, d);
    kInflorescenceBranchAngleMale: 
      MFD(pInflor[kGenderMale].BranchAngle, v, ft, d);
    kInflorescenceInternodeAngleMale: 
      MFD(pInflor[kGenderMale].angleBetweenInternodes, v, ft, d);
    kInflorescencePedicelAngleMale: 
      MFD(pInflor[kGenderMale].PedicelAngle, v, ft, d);
    kInflorescencePeduncleAngleFromVegetativeStemMale: 
      MFD(pInflor[kGenderMale].peduncleAngleFromVegetativeStem, v, ft, d);
    kInflorescencePeduncleAngleFromVegetativeStemApicalMale: 
      MFD(pInflor[kGenderMale].apicalStalkAngleFromVegetativeStem, v, ft, d);
    kInflorescenceFlowersSpiralOnStemMale: 
      MFD(pInflor[kGenderMale].FlowersSpiralOnStem, v, ft, d);
    kInflorescenceIsHeadMale: 
      MFD(pInflor[kGenderMale].IsHead, v, ft, d);
    kInflorescenceTerminalStalkLengthMale: 
      MFD(pInflor[kGenderMale].TerminalStalkLength_mm, v, ft, d);
    kInflorescencePeduncleLengthMale: 
      MFD(pInflor[kGenderMale].PeduncleLength_mm, v, ft, d);
    kInflorescenceInternodeLengthMale: 
      MFD(pInflor[kGenderMale].InternodeLength_mm, v, ft, d);
    kInflorescencePedicelLengthMale: 
      MFD(pInflor[kGenderMale].PedicelLength_mm, v, ft, d);
    kInflorescenceInternodeWidthMale: 
      MFD(pInflor[kGenderMale].InternodeWidth_mm, v, ft, d);
    kInflorescencePedicelTaperIndexMale: 
      MFD(pInflor[kGenderMale].pedicelTaperIndex, v, ft, d);
    kInflorescenceIsTerminalMale: 
      MFD(pInflor[kGenderMale].IsTerminal, v, ft, d);
    kInflorescenceBiomassRequiredMale: 
      MFD(pInflor[kGenderMale].optimalBiomass_pctMPB, v, ft, d);
    kInflorescenceMinFractOptBiomassToCreateMale: 
      MFD(pInflor[kGenderMale].MinFractionOfOptimalBiomassToCreateInflorescence_frn, v, ft, d);
    kInflorescenceMinFractOptBiomassForFlowersMale: 
      MFD(pInflor[kGenderMale].MinFractionOfOptimalBiomassToMakeFlowers_frn, v, ft, d);
    kInflorescenceDaysToAllFlowersShowingMale: 
      MFD(pInflor[kGenderMale].daysToAllFlowersCreated, v, ft, d);
    kInflorescenceFlowersDrawTopToBottomMale: 
      MFD(pInflor[kGenderMale].FlowersDrawTopToBottom, v, ft, d);
    kInflorescenceMinDaysToCreateInflorescenceMale: 
      MFD(pInflor[kGenderMale].MinDaysToCreateInflorescence, v, ft, d);
    kInflorescenceMaxDaysToCreateIfOverMinFractMale: 
      MFD(pInflor[kGenderMale].MaxDaysToCreateInflorescenceIfOverMinFraction, v, ft, d);
    kInflorescenceMinDaysToGrowMale: 
      MFD(pInflor[kGenderMale].MinDaysToGrow, v, ft, d);
    kInflorescenceMaxDaysToGrowMale: 
      MFD(pInflor[kGenderMale].MaxDaysToGrow, v, ft, d);
    kInflorescenceMaleBractNumBracts: 
      MFD(pInflor[kGenderMale].bractTdoParams.repetitions, v, ft, d);
    kInflorescenceMaleBractObject3D: 
      transferObject3D(d, pInflor[kGenderMale].bractTdoParams.object3D, KfObject3D(v));
    kInflorescenceMaleBractScaleAtFullSize: 
      MFD(pInflor[kGenderMale].bractTdoParams.scaleAtFullSize, v, ft, d);
    kInflorescenceMaleBractObject3DXRotationBeforeDraw: 
      MFD(pInflor[kGenderMale].bractTdoParams.xRotationBeforeDraw, v, ft, d);
    kInflorescenceMaleBractObject3DYRotationBeforeDraw: 
      MFD(pInflor[kGenderMale].bractTdoParams.yRotationBeforeDraw, v, ft, d);
    kInflorescenceMaleBractObject3DZRotationBeforeDraw: 
      MFD(pInflor[kGenderMale].bractTdoParams.zRotationBeforeDraw, v, ft, d);
    kInflorescenceMaleBractFaceColor: 
      MFD(pInflor[kGenderMale].bractTdoParams.faceColor, v, ft, d);
    kInflorescenceMaleBractBackfaceColor: 
      MFD(pInflor[kGenderMale].bractTdoParams.backfaceColor, v, ft, d);
    kInflorescenceMaleBractsAreRadiallyArranged: 
      MFD(pInflor[kGenderMale].bractTdoParams.radiallyArranged, v, ft, d);
    kInflorescenceMaleBractObject3DPullbackAngle: 
      MFD(pInflor[kGenderMale].bractTdoParams.pullBackAngle, v, ft, d);
    kFlowerNumPistilsFemale: 
      MFD(pFlower[kGenderFemale].numPistils, v, ft, d);
    kFlowerStyleLengthFemale: 
      MFD(pFlower[kGenderFemale].styleLength_mm, v, ft, d);
    kFlowerStyleWidthFemale: 
      MFD(pFlower[kGenderFemale].styleWidth_mm, v, ft, d);
    kFlowerStyleTaperIndexFemale: 
      MFD(pFlower[kGenderFemale].styleTaperIndex, v, ft, d);
    kFlowerStigmaFemaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderFemale].tdoParams[kPistils].pullBackAngle, v, ft, d);
    kFlowerStyleColorFemale: 
      MFD(pFlower[kGenderFemale].styleColor, v, ft, d);
    kFlowerStigmaNumSectionsFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kPistils].repetitions, v, ft, d);
    kFlowerFemaleStigmaObject3D: 
      transferObject3D(d, pFlower[kGenderFemale].tdoParams[kPistils].object3D, KfObject3D(v));
    kFlowerStigmaScaleAtFullSizeFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kPistils].scaleAtFullSize, v, ft, d);
    kFlowerFemaleStigmaObject3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kPistils].xRotationBeforeDraw, v, ft, d);
    kFlowerFemaleStigmaObject3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kPistils].yRotationBeforeDraw, v, ft, d);
    kFlowerFemaleStigmaObject3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kPistils].zRotationBeforeDraw, v, ft, d);
    kFlowerStigmaFemaleFaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kPistils].faceColor, v, ft, d);
    kFlowerStigmaFemaleBackfaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kPistils].backfaceColor, v, ft, d);
    kFlowerStigmaSectionsAreRadiallyArrangedFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kPistils].radiallyArranged, v, ft, d);
    kFlowerNumStamensFemale: 
      MFD(pFlower[kGenderFemale].numStamens, v, ft, d);
    kFlowerFilamentLengthFemale: 
      MFD(pFlower[kGenderFemale].filamentLength_mm, v, ft, d);
    kFlowerFilamentWidthFemale: 
      MFD(pFlower[kGenderFemale].filamentWidth_mm, v, ft, d);
    kFlowerFilamentTaperIndexFemale: 
      MFD(pFlower[kGenderFemale].filamentTaperIndex, v, ft, d);
    kFlowerFilamentColorFemale: 
      MFD(pFlower[kGenderFemale].filamentColor, v, ft, d);
    kFlowerAntherFemaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderFemale].tdoParams[kStamens].pullBackAngle, v, ft, d);
    kFlowerAntherNumSectionsFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kStamens].repetitions, v, ft, d);
    kFlowerFemaleAntherObject3D: 
      transferObject3D(d, pFlower[kGenderFemale].tdoParams[kStamens].object3D, KfObject3D(v));
    kFlowerAntherScaleAtFullSizeFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kStamens].scaleAtFullSize, v, ft, d);
    kFlowerFemaleAntherObject3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kStamens].xRotationBeforeDraw, v, ft, d);
    kFlowerFemaleAntherObject3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kStamens].yRotationBeforeDraw, v, ft, d);
    kFlowerFemaleAntherObject3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kStamens].zRotationBeforeDraw, v, ft, d);
    kFlowerAntherFemaleFaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kStamens].faceColor, v, ft, d);
    kFlowerAntherFemaleBackfaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kStamens].backfaceColor, v, ft, d);
    kFlowerAntherSectionsAreRadiallyArrangedFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kStamens].radiallyArranged, v, ft, d);
    kFlowerPetal2NumPetalsFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kSecondPetals].repetitions, v, ft, d);
    kFlowerFemalePetal2Object3D: 
      transferObject3D(d, pFlower[kGenderFemale].tdoParams[kSecondPetals].object3D, KfObject3D(v));
    kFlowerPetal2ScaleAtFullSizeFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kSecondPetals].scaleAtFullSize, v, ft, d);
    kFlowerFemalePetal2Object3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kSecondPetals].xRotationBeforeDraw, v, ft, d);
    kFlowerFemalePetal2Object3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kSecondPetals].yRotationBeforeDraw, v, ft, d);
    kFlowerFemalePetal2Object3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kSecondPetals].zRotationBeforeDraw, v, ft, d);
    kFlowerPetal2FemaleFaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kSecondPetals].faceColor, v, ft, d);
    kFlowerPetal2FemaleBackfaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kSecondPetals].backfaceColor, v, ft, d);
    kFlowerPetal2PetalsAreRadiallyArrangedFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kSecondPetals].radiallyArranged, v, ft, d);
    kFlowerPetal2FemaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderFemale].tdoParams[kSecondPetals].pullBackAngle, v, ft, d);
    kFlowerPetal3NumPetalsFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kThirdPetals].repetitions, v, ft, d);
    kFlowerFemalePetal3Object3D: 
      transferObject3D(d, pFlower[kGenderFemale].tdoParams[kThirdPetals].object3D, KfObject3D(v));
    kFlowerPetal3ScaleAtFullSizeFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kThirdPetals].scaleAtFullSize, v, ft, d);
    kFlowerFemalePetal3Object3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kThirdPetals].xRotationBeforeDraw, v, ft, d);
    kFlowerFemalePetal3Object3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kThirdPetals].yRotationBeforeDraw, v, ft, d);
    kFlowerFemalePetal3Object3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kThirdPetals].zRotationBeforeDraw, v, ft, d);
    kFlowerPetal3FemaleFaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kThirdPetals].faceColor, v, ft, d);
    kFlowerPetal3FemaleBackfaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kThirdPetals].backfaceColor, v, ft, d);
    kFlowerPetal3PetalsAreRadiallyArrangedFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kThirdPetals].radiallyArranged, v, ft, d);
    kFlowerPetal3FemaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderFemale].tdoParams[kThirdPetals].pullBackAngle, v, ft, d);
    kFlowerPetal4NumPetalsFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kFourthPetals].repetitions, v, ft, d);
    kFlowerFemalePetal4Object3D: 
      transferObject3D(d, pFlower[kGenderFemale].tdoParams[kFourthPetals].object3D, KfObject3D(v));
    kFlowerPetal4ScaleAtFullSizeFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kFourthPetals].scaleAtFullSize, v, ft, d);
    kFlowerFemalePetal4Object3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kFourthPetals].xRotationBeforeDraw, v, ft, d);
    kFlowerFemalePetal4Object3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kFourthPetals].yRotationBeforeDraw, v, ft, d);
    kFlowerFemalePetal4Object3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kFourthPetals].zRotationBeforeDraw, v, ft, d);
    kFlowerPetal4FemaleFaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kFourthPetals].faceColor, v, ft, d);
    kFlowerPetal4FemaleBackfaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kFourthPetals].backfaceColor, v, ft, d);
    kFlowerPetal4PetalsAreRadiallyArrangedFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kFourthPetals].radiallyArranged, v, ft, d);
    kFlowerPetal4FemaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderFemale].tdoParams[kFourthPetals].pullBackAngle, v, ft, d);
    kFlowerPetal5NumPetalsFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kFifthPetals].repetitions, v, ft, d);
    kFlowerFemalePetal5Object3D: 
      transferObject3D(d, pFlower[kGenderFemale].tdoParams[kFifthPetals].object3D, KfObject3D(v));
    kFlowerPetal5ScaleAtFullSizeFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kFifthPetals].scaleAtFullSize, v, ft, d);
    kFlowerFemalePetal5Object3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kFifthPetals].xRotationBeforeDraw, v, ft, d);
    kFlowerFemalePetal5Object3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kFifthPetals].yRotationBeforeDraw, v, ft, d);
    kFlowerFemalePetal5Object3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kFifthPetals].zRotationBeforeDraw, v, ft, d);
    kFlowerPetal5FemaleFaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kFifthPetals].faceColor, v, ft, d);
    kFlowerPetal5FemaleBackfaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kFifthPetals].backfaceColor, v, ft, d);
    kFlowerPetal5PetalsAreRadiallyArrangedFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kFifthPetals].radiallyArranged, v, ft, d);
    kFlowerPetal5FemaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderFemale].tdoParams[kFifthPetals].pullBackAngle, v, ft, d);
    kFlowerSepalNumPetalsFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kSepals].repetitions, v, ft, d);
    kFlowerFemaleSepalObject3D: 
      transferObject3D(d, pFlower[kGenderFemale].tdoParams[kSepals].object3D, KfObject3D(v));
    kFlowerSepalScaleAtFullSizeFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kSepals].scaleAtFullSize, v, ft, d);
    kFlowerFemaleSepalObject3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kSepals].xRotationBeforeDraw, v, ft, d);
    kFlowerFemaleSepalObject3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kSepals].yRotationBeforeDraw, v, ft, d);
    kFlowerFemaleSepalObject3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kSepals].zRotationBeforeDraw, v, ft, d);
    kFlowerSepalFemaleFaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kSepals].faceColor, v, ft, d);
    kFlowerSepalFemaleBackfaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kSepals].backfaceColor, v, ft, d);
    kFlowerSepalPetalsAreRadiallyArrangedFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kSepals].radiallyArranged, v, ft, d);
    kFlowerSepalFemaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderFemale].tdoParams[kSepals].pullBackAngle, v, ft, d);
    kFlowerFemaleBudOption: 
      MFD(pFlower[kGenderFemale].budDrawingOption, v, ft, d);
    kFlowerBudNumPetalsFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kBud].repetitions, v, ft, d);
    kFlowerFemaleBudObject3D: 
      transferObject3D(d, pFlower[kGenderFemale].tdoParams[kBud].object3D, KfObject3D(v));
    kFlowerBudScaleAtFullSizeFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kBud].scaleAtFullSize, v, ft, d);
    kFlowerFemaleBudObject3DXRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kBud].xRotationBeforeDraw, v, ft, d);
    kFlowerFemaleBudObject3DYRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kBud].yRotationBeforeDraw, v, ft, d);
    kFlowerFemaleBudObject3DZRotationBeforeDraw: 
      MFD(pFlower[kGenderFemale].tdoParams[kBud].zRotationBeforeDraw, v, ft, d);
    kFlowerBudFemaleFaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kBud].faceColor, v, ft, d);
    kFlowerBudFemaleBackfaceColor: 
      MFD(pFlower[kGenderFemale].tdoParams[kBud].backfaceColor, v, ft, d);
    kFlowerBudPetalsAreRadiallyArrangedFemale: 
      MFD(pFlower[kGenderFemale].tdoParams[kBud].radiallyArranged, v, ft, d);
    kFlowerBudFemaleObject3DPullbackAngle: 
      MFD(pFlower[kGenderFemale].tdoParams[kBud].pullBackAngle, v, ft, d);
    end;
  end;


end.
